Node: fMRI_pipeline.preprocessing_stage.motion_correction
Working directory: /home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/fMRI_pipeline/preprocessing_stage/motion_correction

Node inputs:

args = <undefined>
bins = <undefined>
cost = <undefined>
dof = <undefined>
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
in_file = <undefined>
init = <undefined>
interpolation = <undefined>
mean_vol = True
out_file = <undefined>
output_type = NIFTI_GZ
ref_file = <undefined>
ref_vol = <undefined>
rotation = <undefined>
save_mats = False
save_plots = True
save_rms = <undefined>
scaling = <undefined>
smooth = <undefined>
stages = <undefined>
stats_imgs = True
use_contour = <undefined>
use_gradient = <undefined>

Traceback (most recent call last):
  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node motion_correction.

Cmdline:
	mcflirt -in /home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/fMRI_pipeline/preprocessing_stage/converter/fMRI_despike.nii.gz -meanvol -out /home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/fMRI_pipeline/preprocessing_stage/motion_correction/fMRI_despike_mcf.nii.gz -plots -stats
Stdout:

Stderr:

Traceback:
	Traceback (most recent call last):
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 'mean_img' trait of a MCFLIRTOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/fMRI_pipeline/preprocessing_stage/motion_correction/fMRI_despike_mcf_mean_reg.nii.gz' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 400, in run
	    outputs = self.aggregate_outputs(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/fMRI_pipeline/preprocessing_stage/motion_correction/fMRI_despike_mcf_mean_reg.nii.gz' for output 'mean_img' of a MCFLIRT interface

